ministryofjustice/opg-search-service

.circleci/config.yml, README.md, cache/cache.go, cache/cache_test.go, docker-compose.env, docker-compose.yml, go.mod, go.sum, main.go, main_test.go, middleware/jwt_auth.go, middleware/jwt_auth_test.go, scripts/localstack/localstack_init.sh
This PR is to amend the search service to fetch and cache the JWT secret and user has salt from AWS Secrets Manager instead of environment variables. This will allow the secrets to be rotated without requiring a restart. This includes the inclusion of the cache package and associated tests.
=> Sw 3573 Fetch and Cache secrets from AWS Secrets Manager

cli/create_indices.go, cli/create_indices_test.go, elasticsearch/client.go, elasticsearch/client_mock.go, elasticsearch/client_test.go
If provided, and the index exists, it forcibly deletes the index and creates a new one
=> Add `-force` parameter to CLI index creation

main.go, main_test.go
If the `person` index doesn't exist when the service is starting, create it.
This ensures that the index has been created before we add any data to it.
=> Create index when starting the service

elasticsearch/client.go, elasticsearch/client_mock.go, elasticsearch/client_test.go, main.go, main_test.go, person/index_handler.go, person/index_handler_test.go, response/index_response.go
I will follow this up with a PR to simplify the response after I've updated Sirius to not expect `results`
=> VEGA-871 Add simple stats to response from indexing

person/search_handler.go, person/search_handler_test.go
- Find entries based on the search query
- Perform aggregations to get count of each peron type matching the query
- Filter the actual results array to the requested types
Otherwise the aggregations will also take the filter on board, so if you request personType:Donor, it will only tell you how many donors match the search query.
For VEGA-870
=> Apply personType filter after aggregation

.github/workflows/build.yml
Dependabot doesn't have necessary permissions to create a Git tag or push containers (because it's external), so don't try and run this job on Dependabot PRs.
#patch
=> Don't push containers from dependabot

cli/reindex.go, elasticsearch/client.go, internal/cmd/reindex/db.go, internal/cmd/reindex/db_test.go, internal/cmd/reindex/elasticsearch.go, internal/cmd/reindex/reindex.go
Ran in ~2 hours, but
```
{"level":"info","msg":"indexing done successful=19592153 failed=20360245","time":"2022-01-06T09:20:51Z"}
```
which I think is because it got a bit stuck half way through
This should slow indexing down more when ~Elastic~ OpenSearch complains about too many requests.
=> VEGA-1128 Increase backoff with retries

elasticsearch/client.go, internal/cmd/reindex/elasticsearch.go
Something else seems to be the issue, but since it is within the batches that the failure is happening the previous logging didn't show anything. I'm assuming that the same thing is affecting everything in the batch so just logging 1 per, otherwise there will be a lot to look through.
=> VEGA-1128 Capture and log an error if bulk index has failures

.gitignore, cli/commands.go, cli/commands_test.go, cli/create_indices.go, cli/create_indices_test.go, cli/health_check.go, cli/health_check_test.go, cli/index.go, cli/index_test.go, cli/reindex.go, cli/reindex_test.go, internal/cmd/index/batch_iter.go, internal/cmd/index/batch_iter_test.go, internal/cmd/index/db.go, internal/cmd/index/db_test.go, internal/cmd/index/elasticsearch.go, internal/cmd/index/elasticsearch_test.go, internal/cmd/index/index.go, main.go
Currently everything is a global flag, which means we wouldn't be able to introduce something else with `-force`, for example. This makes things callable as subcommands, which can then define their own flagset.
```sh
search-service -create-indices -force
search-service create-indices -force
```
To allow transitioning existing uses `-hc` and `-create-indices` can still be called the old way too.
This also:
- renames everything `reindex` to `index`
- adds an `-all` flag so you don't have to specify an ID range
- removes the `opg-search-service` binary from the repo, and adds it to the `.gitignore`
=> VEGA-1128 Make commands act like subcommands

cli/create_indices.go, cli/create_indices_test.go, cli/index.go, cli/index_test.go, elasticsearch/client.go, elasticsearch/client_mock.go, elasticsearch/client_test.go, internal/cmd/index/elasticsearch.go, internal/cmd/index/elasticsearch_test.go, internal/cmd/index/index.go, main.go, main_test.go, person/index_handler.go, person/index_handler_test.go, person/person.go, person/person_test.go, person/search_handler.go, person/search_handler_test.go
I ended up refactoring things to make it easier to pass around a name for the index. 
- `IndexConfig()` is now a function instead of a method on `person.Person`, and returns the name for the index too. It has always seemed a bit daft to me having it on `person.Person` when it didn't use any fields or other methods.
- I moved the create index logic onto `elasticsearch.Client` so it didn't need to be duplicated between the CLI command and `main`.
Also realised that we'd want the `index` command to do `person` by default, so added a `--hash` flag to switch when running on AWS.
=> VEGA-1160 Index to person and person_hash

person/search_request.go
It isn't useful to us and can contain confidential information, such as tying a person to a case ID, or to an address #patch
=> Stop logging search term

cli/create_indices.go, cli/create_indices_test.go, cli/index.go, main.go, main_test.go, person/index_handler.go, person/index_handler_test.go, person/person.go, person/search_handler.go, person/search_handler_test.go
Reverts ministryofjustice/opg-search-service#145
Because the index in the code doesn't match the existing index we need to undo this change while the differences are figured out
=> Revert "VEGA-1161 Only use index containing hash"

internal/cmd/create_indices.go, internal/cmd/create_indices_test.go, internal/elasticsearch/client_mock.go
When forced to delete and recreate an index, also create the alias if it's missing.
Otherwise, the alias gets removed and the next indexing request will auto-create a `person` index with incorrect configuration.
=> Create an alias when force-creating the index #patch

internal/elasticsearch/client.go, internal/elasticsearch/client_test.go, internal/remove/handler.go, internal/remove/handler_test.go
It should be a query parameter, not part of the request body
#patch
=> Change location of conflicts=proceed

internal/person/person.go, internal/search/query.go, internal/search/query_test.go, internal/search/search_request_test.go, main_test.go
This does change searches on other fields too. It returns "fuzzier" matches (which I think is what we want to happen anyway). For example, if we have:
```
| John Doe | 123 Fake Street | 
| Jane Doe | 123 Other Street |
```
A search for `123 Fake Street` will return both, but ordered with John first as that is the best match, the previous behaviour would be to return only John.
=> VEGA-1372 Allow searching postcodes with and without spaces

internal/person/person.go
Background:
Bug SW-6348 will be fixed with an ElasticSearch  re-index. Ran via ECS commands on Adhoc ok
The favoured way to trigger an ElasticSearch re-index on prod is to make an ‘innocuous change’ to the go config, which tricks ES into building a new index when it sees the different hash.
Adding whitespace to this file doesn’t trigger a new hash but adding another field as per this PR works... not sure if it's overkill though
=> Innocous change to config will trigger a new ES index

internal/cmd/cleanup_indices.go, internal/cmd/cleanup_indices_test.go, internal/cmd/create_indices.go, internal/cmd/create_indices_test.go, internal/cmd/update_alias.go, internal/cmd/update_alias_test.go, internal/elasticsearch/client.go, internal/elasticsearch/client_mock.go, internal/elasticsearch/client_test.go, internal/index/handler.go, internal/index/handler_test.go, internal/index/indexer.go, internal/index/indexer_test.go, internal/remove/handler.go, internal/remove/handler_test.go, internal/search/handler.go, internal/search/handler_test.go, main.go, main_test.go
now using `http.NewRequestWithContext` instead of just `http.NewRequest` so when the parent call is cancelled, any in-flight child requests will also be cancelled, and correctly cascade
Also changed error code to `499` for cancelled search requests
=> VEGA-1576-cancelled-requests-bug

internal/elasticsearch/client.go, internal/elasticsearch/client_test.go, main_test.go
This adds an `_index` field to each search result, which is the name of the ElasticSearch index minus the hash suffix (i.e. `_index` will be "poadraftapplication" rather than "poadraftapplication_a12adsre").
I think this solution is a bit ugly, so if anyone has a more elegant approach, please make suggestions.
=> VEGA-2000 Include index name in search results #minor

internal/search/handler.go, internal/search/handler_test.go, internal/search/query.go, internal/search/query_test.go, internal/search/search_request.go, internal/search/search_request_test.go, main.go
This defaults to all indices. Use an "indices" property in the search request to limit to particular indices. Choices are "person", "firm", "poadraftapplication"; pass as an array in the JSON POST body to the /searchAll endpoint.
=> VEGA-1988 Select indices when calling /searchAll #minor

internal/poadraftapplication/db.go, internal/poadraftapplication/db_test.go, internal/poadraftapplication/index_request_test.go, internal/poadraftapplication/poa_draft_application.go, internal/testdata/schema.sql
`donorname` no longer exists in the `poa.draft_applications` table and has been replaced with separate fields for `donorfirstnames` and `donorlastname`. This PR is to reflect those changes here in the search service
VEGA-2020 #patch
=> VEGA-2020 separate draft application donor name fields

internal/elasticsearch/client.go, internal/elasticsearch/client_test.go, internal/index/handler_test.go, internal/index/indexer_test.go, internal/middleware/jwt_auth.go, internal/remove/handler_test.go, main.go, main_test.go
- Checking the error response of functions in tests
- Handling gradeful shutdown better (signal must be buffered, os.Kill can't be trapped, cancelFn must be handled)
- Use `fmt.Errorf(...)` instead of `errors.New(fmt.Sprintf(...))`
- Remove unused properties, structs and consts
#patch
=> Fix errors identified by linting:

internal/elasticsearch/client_test.go
To ensure the signer endpoint is being claled and is attaching a valid-looking Authorization header
For SP-1308
=> Add test for request signing

.github/renovate.json, docker-compose.yml
To match major versioning with what we have deployed in AWS (and in `opg-sirius`)
#patch
=> Fix postgres to 13.12

internal/cmd/cleanup_indices.go, internal/cmd/cleanup_indices_test.go, internal/cmd/create_indices.go, internal/cmd/create_indices_test.go, internal/cmd/index.go, internal/cmd/index_test.go, internal/cmd/update_alias.go, internal/cmd/update_alias_test.go, internal/digitallpa/digital_lpa.go, internal/digitallpa/digital_lpa_test.go, internal/elasticsearch/client.go, internal/firm/firm.go, internal/firm/firm_test.go, internal/person/db_test.go, internal/person/person.go, internal/person/person_test.go, main.go, main_test.go
The idea is that the alias for an index and the real name of the index are held together, so we don't have to guess the alias from the real name at any point. This generally makes managing indices cleaner, too, as we are passing fewer arguments around.
=> VEGA-2529 Improve alias parsing so it may contain underscores (like digital_lpa) #minor

.github/workflows/pact-provider-verification.yml
GitHub Actions runners don't support the v1 syntax any more
Fixes CTC-162 #patch
=> `docker-compose` -> `docker compose`
